# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 16:38
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='Enter your comment here', max_length=50)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='publish_time')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(blank=True, default='张三', max_length=40)),
                ('phone', models.CharField(blank=True, default='18800000000', max_length=40)),
                ('school', models.CharField(blank=True, default='Sun Yat-Sen University', max_length=40)),
                ('department', models.CharField(blank=True, default='School of Data and Computer Science', max_length=40)),
                ('major', models.CharField(blank=True, default='Software Engineering', max_length=40)),
                ('grade', models.CharField(blank=True, default='2013', max_length=40)),
                ('description', models.TextField(blank=True, default='This is a description')),
                ('role', models.CharField(blank=True, choices=[('common', 'common'), ('special', 'special')], default='common', max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=['tag1', 'tag2', 'tag3'], size=None)),
                ('commentList', models.ManyToManyField(related_name='profileCommented', to='teamBuilder.Comment')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Demo Project', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='Enter your description here')),
                ('school', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=['Sun Yat-sen University', 'South China University of Technology'], size=None)),
                ('department', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=['School of Data and Computer Science', 'School of Engineering'], size=None)),
                ('major', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=['Software Engineering', 'Computer Science and Technology'], size=None)),
                ('deadline', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='deadline')),
                ('min_num', models.PositiveIntegerField(blank=True, default=3)),
                ('max_num', models.PositiveIntegerField(blank=True, default=10)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_published', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Demo Team', max_length=20, unique=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=['tag1', 'tag2', 'tag3'], size=None)),
                ('description', models.TextField(default='Enter your description here')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_special', models.BooleanField(default=False)),
                ('memberList', models.ManyToManyField(related_name='teamAsMember', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamAsCaptain', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamEnroll', to='teamBuilder.Project')),
            ],
        ),
    ]
