# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 07:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
