# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamBuilder', '0003_auto_20160525_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
