# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamBuilder', '0004_team_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='is_accepted',
            new_name='is_confirmed',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('normal', 'normal'), ('special', 'special')], max_length=20, null=True),
        ),
    ]
