# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamBuilder', '0011_auto_20160526_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(default='This is a description'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(default='This is a comment', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('common', 'common'), ('special', 'special')], max_length=20, null=True),
        ),
    ]
