# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamBuilder', '0015_auto_20160526_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restriction',
            name='department',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='restriction',
            name='major',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='restriction',
            name='school',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
