# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamBuilder', '0020_auto_20160529_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(blank=True, default='School of Data and Computer Science', max_length=40),
        ),
        migrations.AddField(
            model_name='project',
            name='major',
            field=models.CharField(blank=True, default='Software Engineering', max_length=40),
        ),
        migrations.AddField(
            model_name='project',
            name='max_num',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='min_num',
            field=models.PositiveIntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='school',
            field=models.CharField(blank=True, default='Sun Yat-Sen University', max_length=40),
        ),
    ]
